#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

# =========================
# Elasticsearch image
# =========================
elasticsearch_registry_endpoint: "{{ lookup('env', 'ELASTICSEARCH_REGISTRY_ENDPOINT') or 'docker.io/library' }}"
elasticsearch_image_name: "elasticsearch"
elasticsearch_image_tag: "8.19.6"
elasticsearch_image: "{{ elasticsearch_registry_endpoint }}/{{ elasticsearch_image_name }}:{{ elasticsearch_image_tag }}"
elasticsearch_container_name: "{{ inventory_hostname }}"

# =========================
# Elasticsearch Paths
# =========================
elasticsearch_remote_config_dir: "{{ remote_config_dir }}"
elasticsearch_container_config_dir: "/usr/share/elasticsearch"

# =========================
# TLS Settings
# =========================
elasticsearch_use_tls: false
