#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Fetch the logs from the Postgres Exporter Sidecar container
  vars:
    container_logs_file: "{{ postgres_exporter_container_name }}_logs.txt"
  ansible.builtin.include_role:
    name: hyperledger.fabricx.container
    tasks_from: fetch_logs
