#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Start Fabric-X Orderer Assembler
  vars:
    container_name: "{{ orderer_container_name }}"
    container_image: "{{ orderer_image }}"
    container_command: "assembler --config={{ orderer_docker_config_dir }}/{{ orderer_config_file }}"
    container_ports:
      - "{{ orderer_rpc_port }}:{{ orderer_rpc_port }}"
    container_volumes:
      - "{{ orderer_remote_config_dir }}:{{ orderer_docker_config_dir }}:Z"
    container_wait_until_running: true
    container_wait_port: "{{ orderer_rpc_port }}"
    container_run_as_host_user: true
  ansible.builtin.include_role:
    name: hyperledger.fabricx.container
    tasks_from: start
