#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Fetch the Prometheus TLS certificate
  ansible.builtin.fetch:
    src: "{{ prometheus_remote_config_dir }}/tls/{{ prometheus_tls_cert_file }}"
    dest: "{{ fetched_artifacts_dir }}/{{ inventory_hostname }}/tls/tls_cert.pem"
    flat: true
  when:
    - prometheus_use_tls
