#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Fetch the Prometheus TLS CA certificate
  ansible.builtin.fetch:
    src: "{{ prometheus_remote_config_dir }}/tls/ca.crt"
    dest: "{{ fetched_artifacts_dir }}/{{ inventory_hostname }}/tls/ca.crt"
    flat: true
  when:
    - prometheus_use_tls
