#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Remove container networks
  ansible.builtin.import_playbook: hyperledger.fabricx.remove_container_networks
