#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Fetch the Postgres Exporter TLS certificate
  ansible.builtin.fetch:
    src: "{{ postgres_exporter_remote_config_dir }}/tls/tls_cert.pem"
    dest: "{{ fetched_artifacts_dir }}/{{ inventory_hostname }}/tls/tls_cert.pem"
    flat: true
  when:
    - postgres_exporter_use_tls
