#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Remove Postgres Exporter TLS directory
  ansible.builtin.file:
    path: "{{ postgres_exporter_remote_config_dir }}/tls"
    state: absent
  when:
    - postgres_exporter_use_tls
