#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Clean Elasticsearch volume
  vars:
    container_volume_path: "{{ elasticsearch_remote_config_dir }}/data"
  ansible.builtin.include_role:
    name: hyperledger.fabricx.container
    tasks_from: volume/rm
