#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Fetch Hyperledger Fabric-X Orderer consenter logs from container
  ansible.builtin.include_role:
    name: hyperledger.fabricx.orderer
    tasks_from: container/fetch_logs
  when: not orderer_use_bin

- name: Fetch Hyperledger Fabric-X Orderer consenter logs from binary
  ansible.builtin.include_role:
    name: hyperledger.fabricx.orderer
    tasks_from: bin/fetch_logs
  when: orderer_use_bin
