#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Start Fabric-X Committer Validator Persistence containers
  vars:
    container_name: "{{ committer_container_name }}"
    container_image: "{{ committer_image }}"
    container_command: "committer start-vc --config={{ committer_docker_config_dir }}/{{ committer_validator_config_file }}"
    container_ports:
      - "{{ committer_rpc_port }}:{{ committer_rpc_port }}"
      - "{{ prometheus_exporter_port }}:{{ prometheus_exporter_port }}"
    container_volumes:
      - "{{ committer_remote_config_dir }}/{{ committer_validator_config_file }}:{{ committer_docker_config_dir }}/{{ committer_validator_config_file }}"
    container_wait_until_running: true
    container_run_as_host_user: true
    container_wait_port: "{{ committer_rpc_port }}"
    container_wait_timeout: 120
  ansible.builtin.include_role:
    name: hyperledger.fabricx.container
    tasks_from: start
