#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Setup the crypto material for Fabric-X Orderers
  hosts: "{{ target_hosts | default('fabric_x_orderers') }}:&fabric_x_orderers"
  tasks:
    - name: Setup Hyperledger Fabric-X Orderer crypto material
      ansible.builtin.include_role:
        name: hyperledger.fabricx.orderer
        tasks_from: crypto/setup
    - name: Fetch Hyperledger Fabric-X Orderer certificates
      ansible.builtin.include_role:
        name: hyperledger.fabricx.orderer
        tasks_from: crypto/fetch
