#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Find the container client to use
  ansible.builtin.include_role:
    name: hyperledger.fabricx.container
    tasks_from: get_container_client
  when:
    - container_client == ''

- name: Login into Container Registry with podman
  ansible.builtin.include_role:
    name: hyperledger.fabricx.container
    tasks_from: podman/login
  when:
    - container_client == 'podman'

- name: Login into Container Registry with docker
  ansible.builtin.include_role:
    name: hyperledger.fabricx.container
    tasks_from: docker/login
  when:
    - container_client == 'docker'
