#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Start Hyperledger Fabric-X Committer QueryService container
  ansible.builtin.include_role:
    name: hyperledger.fabricx.committer
    tasks_from: query_service/container/start
  when: not committer_use_bin

- name: Start Hyperledger Fabric-X Committer QueryService binary
  ansible.builtin.include_role:
    name: hyperledger.fabricx.committer
    tasks_from: query_service/bin/start
  when: committer_use_bin
