#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Create dinamically the node_exporter_hosts group of hosts
  hosts: "{{ target_hosts | default('all') }}"
  tasks:
    - name: Retrieve the Node Exporter hosts
      ansible.builtin.include_role:
        name: hyperledger.fabricx.node_exporter
        tasks_from: get_host_set

- name: Wipe Node Exporter
  hosts: "{{ target_hosts | default('node_exporter_hosts') }}:&node_exporter_hosts"
  tasks:
    - name: Wipe the Node Exporter instances
      ansible.builtin.include_role:
        name: hyperledger.fabricx.node_exporter
        tasks_from: wipe
