#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Fetch the Node Exporter TLS certificate
  ansible.builtin.fetch:
    src: "{{ node_exporter_remote_config_dir }}/tls/{{ node_exporter_tls_cert_file }}"
    dest: "{{ fetched_artifacts_dir }}/{{ inventory_hostname }}/tls/tls_cert.pem"
    flat: true
  when:
    - node_exporter_use_tls
