#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Fetch the Node Exporter TLS CA certificate
  ansible.builtin.fetch:
    src: "{{ node_exporter_remote_config_dir }}/tls/ca.crt"
    dest: "{{ fetched_artifacts_dir }}/{{ inventory_hostname }}/tls/ca.crt"
    flat: true
  when:
    - node_exporter_use_tls

- name: Fetch the Node Exporter TLS certificate
  ansible.builtin.fetch:
    src: "{{ node_exporter_remote_config_dir }}/tls/server.crt"
    dest: "{{ fetched_artifacts_dir }}/{{ inventory_hostname }}/tls/server.crt"
    flat: true
  when:
    - node_exporter_use_tls
