#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Clean Postgres config folder
  ansible.builtin.file:
    path: "{{ postgres_remote_config_dir }}"
    state: absent
