#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Generate the SSL crypto material
  vars:
    openssl_private_key_path: "{{ postgres_remote_tls_dir }}/tls_key.pem"
    openssl_cert_path: "{{ postgres_remote_tls_dir }}/tls_cert.pem"
  ansible.builtin.include_role:
    name: hyperledger.fabricx.openssl
    tasks_from: generate_self_signed_cert
  when:
    - postgres_use_tls
