#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Clean ElasticSearch TLS key
  vars:
    container_volume_path: "{{ elasticsearch_remote_config_dir }}/tls/{{ elasticsearch_tls_private_key_file }}"
  ansible.builtin.include_role:
    name: hyperledger.fabricx.container
    tasks_from: volume/rm

- name: Clean ElasticSearch TLS folder
  ansible.builtin.file:
    path: "{{ elasticsearch_remote_config_dir }}/tls"
    state: absent
