#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Clean ElasticSearch config folder
  ansible.builtin.file:
    path: "{{ elasticsearch_remote_config_dir }}"
    state: absent
