#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Remove Postgres Exporter config files
  ansible.builtin.file:
    path: "{{ postgres_exporter_remote_config_dir }}"
    state: absent
