#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Login podman within {{ container_registry }}
  containers.podman.podman_login:
    registry: "{{ container_registry }}"
    username: "{{ container_registry_username }}"
    password: "{{ container_registry_password }}"
