#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Remove Jaeger config directory
  ansible.builtin.file:
    path: "{{ jaeger_remote_config_dir }}"
    state: absent
