#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Copy TLS cert
  ansible.builtin.copy:
    src: "{{ fetched_tls_dir }}/{{ inventory_hostname }}/tls_cert.pem"
    dest: "{{ yugabyte_remote_tls_dir }}/tls_cert.pem"
    mode: "0o644"
  when:
    - yugabyte_use_tls

- name: Copy TLS CA cert
  ansible.builtin.copy:
    src: "{{ fetched_tls_dir }}/yugabyte-cluster-{{ yugabyte_cluster_id }}/tls_cert.pem"
    dest: "{{ yugabyte_remote_tls_dir }}/ca.pem"
    mode: "0o644"
  when:
    - yugabyte_use_tls
