#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Remove Prometheus container
  ansible.builtin.include_role:
    name: hyperledger.fabricx.prometheus
    tasks_from: container/rm

- name: Remove Prometheus container data
  ansible.builtin.include_role:
    name: hyperledger.fabricx.prometheus
    tasks_from: container/clean

- name: Remove Prometheus crypto files
  ansible.builtin.include_role:
    name: hyperledger.fabricx.prometheus
    tasks_from: crypto/rm

- name: Remove Prometheus configuration files
  ansible.builtin.include_role:
    name: hyperledger.fabricx.prometheus
    tasks_from: config/rm
