#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Fetch OpenSSL CSR on control node
  ansible.builtin.fetch:
    src: "{{ yugabyte_remote_config_dir }}/tls/tls.csr"
    dest: "{{ fetched_artifacts_dir }}/{{ inventory_hostname }}/tls/tls.csr"
    flat: true
  when:
    - yugabyte_use_tls

- name: Fetch OpenSSL extension file on control node
  ansible.builtin.fetch:
    src: "{{ yugabyte_remote_config_dir }}/tls/tls.ext"
    dest: "{{ fetched_artifacts_dir }}/{{ inventory_hostname }}/tls/tls.ext"
    flat: true
  when:
    - yugabyte_use_tls
