#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Remove Yugabyte TLS directory
  ansible.builtin.file:
    path: "{{ yugabyte_remote_config_dir }}/tls"
    state: absent
  when:
    - yugabyte_use_tls
