#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Copy TLS cert
  ansible.builtin.copy:
    src: "{{ fetched_artifacts_dir }}/{{ inventory_hostname }}/tls/tls_cert.pem"
    dest: "{{ yugabyte_remote_config_dir }}/tls/node.{{ ansible_host }}.crt"
    mode: "0o644"
  when:
    - yugabyte_use_tls

- name: Copy TLS CA cert
  ansible.builtin.copy:
    src: "{{ fetched_artifacts_dir }}/yugabyte-cluster-{{ yugabyte_cluster_id }}/tls/tls_cert.pem"
    dest: "{{ yugabyte_remote_config_dir }}/tls/ca.crt"
    mode: "0o644"
  when:
    - yugabyte_use_tls
