#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Stop Fabric CAs
  hosts: "{{ target_hosts | default('fabric_cas') }}:&fabric_cas"
  tasks:
    - name: Stop Fabric CA servers
      ansible.builtin.include_role:
        name: hyperledger.fabricx.fabric_ca
        tasks_from: server/stop
      when:
        - fabric_ca_port is defined
    - name: Stop Fabric CA DBs
      ansible.builtin.include_role:
        name: hyperledger.fabricx.postgres
        tasks_from: stop
      when:
        - postgres_port is defined
