#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

# =========================
# Ansible Connection
# =========================
ansible_connection: ssh
ansible_user: root
ansible_python_interpreter: /usr/bin/python3

# =========================
# Machines to use
# =========================
os: linux
arch: amd64
host_machine_1: "linux1amd64.cloud.com" # <- change these machines endpoints to your machines!
host_machine_2: "linux2amd64.cloud.com"
host_machine_3: "linux3amd64.cloud.com"
host_machine_4: "linux4amd64.cloud.com"
host_machine_5: "linux5amd64.cloud.com"
host_machine_6: "linux6amd64.cloud.com"
host_machine_7: "linux7amd64.cloud.com"
host_machine_8: "linux8amd64.cloud.com"
host_machine_9: "linux9amd64.cloud.com"
host_machine_10: "linux10amd64.cloud.com"
host_machine_11: "linux11amd64.cloud.com"
host_machine_12: "linux12amd64.cloud.com"
host_machine_13: "linux13amd64.cloud.com"
host_machine_14: "linux14amd64.cloud.com"
host_machine_15: "linux15amd64.cloud.com"
host_machine_16: "linux16amd64.cloud.com"

# =========================
# Remote Node paths
# =========================
remote_deploy_dir: "/root/perf-deployment" # <- point this to your SSD volume mount
remote_node_dir: "{{ remote_deploy_dir }}/{{ inventory_hostname }}"
remote_config_dir: "{{ remote_node_dir }}/config"
