#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Set the MSP folder
  vars:
    org_dir: >-
      {{
        'ordererOrganizations'
        if fabric_ca_orderer_organization is defined and fabric_ca_orderer_organization
        else 'peerOrganizations'
      }}
  ansible.builtin.set_fact:
    fabric_ca_org_dir: "{{ fetched_artifacts_dir }}/crypto/{{ org_dir }}/{{ organization.domain }}"

- name: Fetch the CA certificate
  ansible.builtin.fetch:
    src: "{{ fabric_ca_remote_config_dir }}/ca-cert.pem"
    dest: "{{ fabric_ca_org_dir }}/msp/cacerts/ca.{{ organization.domain }}-cert.pem"
    flat: true

- name: Fetch the TLS CA certificate
  ansible.builtin.fetch:
    src: "{{ fabric_ca_remote_config_dir }}/ca-cert.pem"
    dest: "{{ fabric_ca_org_dir }}/msp/tlscacerts/tlsca.{{ organization.domain }}-cert.pem"
    flat: true

# Despite admincerts being deprecated, we must fetch also the admin cert in order to build a proper
# config block for the ordering service.
# If we don't fetch the admin certificate, the genesis block is built without it and the orderers
# fail with the error "administrators must be declared when no admin ou classification is set".
- name: Fetch the Admin CA certificate
  ansible.builtin.fetch:
    src: "{{ fabric_ca_remote_config_dir }}/{{ fabric_ca_admin.name }}/msp/signcerts/cert.pem"
    dest: "{{ fabric_ca_org_dir }}/msp/admincerts/Admin@{{ organization.domain }}-cert.pem"
    flat: true
