#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Ensure the Hyperledger Fabric-X Validators Loadgen config directory exists
  ansible.builtin.file:
    path: "{{ loadgen_remote_config_dir }}"
    state: directory
    mode: "0o755"

- name: Generate the config for the Hyperledger Fabric-X Validators Loadgen
  vars:
    loadgen_config_dir: "{{ loadgen_remote_config_dir if loadgen_use_bin else loadgen_container_config_dir }}"
    committer_validator_ref_host: "{{ committer_validator_hosts | first }}"
  ansible.builtin.template:
    src: "validator-client.yaml.j2"
    dest: "{{ loadgen_remote_config_dir }}/{{ loadgen_config_file }}"
    mode: "0o644"

# =========================
# HLFX Committer Validator TLS
# =========================
- name: Ensure Hyperledger Fabric-X Committer Validators TLS folder exist
  vars:
    committer_validator_ref_host: "{{ committer_validator_hosts | first }}"
  ansible.builtin.file:
    path: "{{ loadgen_remote_config_dir }}/tls/validators"
    state: directory
    mode: "0o755"
  when:
    - hostvars[committer_validator_ref_host].committer_use_tls is defined
    - hostvars[committer_validator_ref_host].committer_use_tls

- name: Transfer Hyperledger Fabric-X Committer Validators TLS CA certificate
  vars:
    committer_validator_ref_host: "{{ committer_validator_hosts | first }}"
  ansible.builtin.copy:
    src: "{{ fetched_artifacts_dir }}/{{ committer_validator_ref_host }}/tls/ca.crt"
    dest: "{{ loadgen_remote_config_dir }}/tls/validators/ca.crt"
    mode: "0o644"
  when:
    - hostvars[committer_validator_ref_host].committer_use_tls is defined
    - hostvars[committer_validator_ref_host].committer_use_tls
