#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

# =========================
# Config
# =========================
- name: Ensure orderer config directory exists
  ansible.builtin.file:
    path: "{{ orderer_remote_config_dir }}"
    state: directory
    mode: "0o755"

- name: Create Fabric-X Orderer Consenter config
  vars:
    orderer_config_dir: >-
      {{
        orderer_remote_config_dir
        if orderer_use_bin
        else orderer_container_config_dir
      }}
  ansible.builtin.template:
    src: config-consenter.yaml.j2
    dest: "{{ orderer_remote_config_file }}"
    mode: "0o640"

# =========================
# Genesis block
# =========================
- name: Copy Genesis block to use for the genesis setup phase
  ansible.builtin.copy:
    src: "{{ configtxgen_artifacts_dir }}/{{ orderer_genesis_block_file }}"
    dest: "{{ orderer_remote_config_dir }}/genesis.block"
    mode: "0o644"

# =========================
# mTLS
# =========================
- name: Transfer mTLS certificates
  ansible.builtin.include_role:
    name: hyperledger.fabricx.orderer
    tasks_from: config/mtls/transfer
  when:
    - orderer_use_mtls
    - orderer_mtls_clients is defined
    - orderer_mtls_clients
      | length > 0
